apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podhealthchecks.monitor.kphc
spec:
  group: monitor.kphc
  names:
    kind: PodHealthCheck
    listKind: PodHealthCheckList
    plural: podhealthchecks
    singular: podhealthcheck
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            dingTalk:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                secret:
                  type: string
                webhook:
                  type: string
              required:
              - webhook
              - secret
              type: object
            healthCheck:
              properties:
                interval:
                  format: int64
                  type: integer
                path:
                  type: string
                port:
                  type: string
                timeout:
                  format: int64
                  type: integer
              required:
              - interval
              - port
              - path
              - timeout
              type: object
            labelSelector:
              additionalProperties:
                type: string
              type: object
            namespace:
              type: string
          required:
          - dingTalk
          - namespace
          - labelSelector
          - healthCheck
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
