kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-pod-health-check
subjects:
- kind: ServiceAccount
  name: kubernetes-pod-health-check
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-pod-health-check
  apiGroup: rbac.authorization.k8s.io
