apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-pod-health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-pod-health-check
  template:
    metadata:
      labels:
        name: kubernetes-pod-health-check
    spec:
      serviceAccountName: kubernetes-pod-health-check
      containers:
        - name: kubernetes-pod-health-check
          # Replace this with the built image name
          image: registry.cn-hangzhou.aliyuncs.com/riet/kubernetes-pod-health-check:v1.0.0
          command:
          - kubernetes-pod-health-check
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubernetes-pod-health-check"
